# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_require 'dotenv'

default_platform(:android)

platform :android do
  before_all do
    Dotenv.overload '.env.secret'
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    firebase_app_distribution(
        app: "1:1077593319207:android:e338f8044f4615eb00eb02",
        firebase_cli_token:ENV['FIREBASE_TOKEN'],
        groups: "qa",
        release_notes: "Lots of amazing new features to test out!"
      )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
      task: "bundle",
      flavor: "WorldDomination",
      build_type: "Release"
    )
    upload_to_play_store(
    aab:"/home/bic-pc/StudioProjects/room-ci-cd/app/release/app-release.aab"
    )
  end
end
